import {StyleSheet} from 'react-native';
module.exports=StyleSheet.create({
    container2:{
        width:'86%',
        height:50,
        backgroundColor:'green',
        opacity:0.8,
        alignItems:'center'
    },
    conatiner:{
      flex:1,
      flexDirection:'row',
    },
    container3:{
      height:50,
      width:50,
      backgroundColor:'green',
      opacity:0.8
    },
    textView:{
        marginTop:7,
        marginLeft:20,
        fontSize:25,
        fontWeight:'bold',
        color:'white'
    },
    popupView:{
      flex:1,
      alignItems:'center',
      justifyContent:'center',
    },
    cadenasView:{
      alignItems:'center',
      marginTop:'15%',
      height:520,
    },
    touchableHighlight:{
        height:100,
        width:'90%',
        marginLeft:'5%',
        borderRadius:5,
        backgroundColor:'white',
        opacity:0.7,
        marginBottom:'5%'
    },
    finalTouchableHighlight:{
      height:100,
        width:'90%',
        marginLeft:'5%',
        borderRadius:5,
        backgroundColor:'white',
        opacity:0.7,
        marginBottom:'20%'
    },
    monContainer:{
      flex:1,
      flexDirection:'row',
      marginBottom:'20%'
    },
    monTruc:{
          height:'75%',
          width:'90%',
          marginLeft:'5%',
          borderRadius:5,
          backgroundColor:'white',
          opacity:0.7,
    },
    card:{
          height:50,
          width:160,
          marginLeft:'5%',
          borderRadius:5,
          opacity:0.8,
    },
    logos:{
      width:'100%',
      height:'100%',
      borderRadius:5,
      opacity:0.8
    },
    backChemin:{
      backgroundColor:'#D09707',
      height:'100%',
      borderRadius:5,
    },
    backCoeur:{
      backgroundColor:'#e83030',
      height:'100%',
      borderRadius:5,
    },
    backEco:{
      backgroundColor:'#281efb',
      height:'100%',
      borderRadius:5,
    },
    backCo2:{
      backgroundColor:'#25B442',
      height:'100%',
      borderRadius:5,
    },
    titreTextCard:{
      fontSize:20,
    },
    vueTextCard:{
      alignItems:'center',
      justifyContent:'center'
    }
  })